name: legal_referral_ui
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  android_id: ^0.4.0
  animated_toggle_switch: ^0.8.0
  any_link_preview: ^3.0.2
  app_links: ^6.3.2
  appinio_social_share: ^0.3.1
  bloc_concurrency: ^0.2.3
  bubble: ^1.2.1
  cached_network_image: ^3.3.1
  camerawesome: ^2.1.0
  carousel_slider: ^5.0.0
  collection: ^1.18.0
  crypto: ^3.0.3
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  device_info_plus: ^10.1.2
  dio: ^5.7.0
  dots_indicator: ^2.1.2
  dropdown_button2: ^2.3.9
  equatable: ^2.0.5
  file_picker: ^8.0.5
  firebase_analytics: ^11.0.0
  firebase_auth: ^5.0.0
  firebase_core: ^3.0.0
  firebase_messaging: ^15.1.2
  firebase_performance: ^0.10.0
  firebase_storage: ^12.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_card_swiper: ^7.0.1
  flutter_chat_types: ^3.6.2
  flutter_chat_ui: ^1.6.12
  flutter_document_picker: ^5.2.3
  flutter_dotenv: ^5.1.0
  flutter_facebook_auth: ^6.0.4
  flutter_layout_grid: ^2.0.6
  flutter_linkify: ^6.0.0
  flutter_local_notifications: ^17.2.3
  flutter_polls: ^0.1.6
  flutter_rating_bar: ^4.0.1
  flutter_screenutil: ^5.9.0
  flutter_spinkit: ^5.2.1
  flutter_staggered_animations: ^1.1.1
  flutter_svg: ^2.0.10+1
  freezed_annotation: ^2.4.1
  get_it: ^7.6.7
  go_router: ^14.0.1
  google_sign_in: ^6.2.1
  grouped_list: ^6.0.0
  image_cropper: ^8.0.2
  image_network: ^2.5.6
  image_picker: ^1.0.7
  injectable: ^2.3.5
  internet_file: ^1.2.0
  intl: ^0.19.0
  introduction_screen: ^3.1.12
  json_annotation: ^4.8.1
  linkedin_login: ^3.0.5
  logger: ^2.2.0
  open_filex: ^4.4.0
  path: ^1.9.0
  path_provider: ^2.1.3
  pdfx: ^2.6.0
  pinput: ^5.0.0
  pretty_dio_logger: ^1.3.1
  retrofit: ^4.1.0
  share_plus: ^10.0.2
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0
  signin_with_linkedin: ^1.0.0
  stream_transform: ^2.1.0
  timeago: ^3.6.0
  timeline_tile: ^2.0.0
  toastification: ^2.0.0
  universal_platform: ^1.0.0+1
  url_launcher: ^6.2.2
  url_strategy: ^0.3.0
  uuid: ^4.3.3
  video_player: ^2.8.7
  video_thumbnail: ^0.5.3
  web_socket_channel: ^3.0.0

dev_dependencies:
  build_runner: ^2.4.9
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.6
  injectable_generator: ^2.4.1
  json_serializable: ^6.7.1
  retrofit_generator: ^9.1.2

dependency_overrides:
  # dio: ^5.4.0
  http: ^1.2.0
  rxdart: ^0.27.7

flutter:
  uses-material-design: true
  assets:
    - assets/logos/
    - assets/images/
    - assets/icons/
    - assets/tempImages/
    # - assets/.env
